### ISSUE TITLE
PRACTICA DE REQUISITOS

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/practica-de-requisitos-tecno-power#1]
[Practica De requisitos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-requisitos-tecno-power/files/7582457/Practica.De.requisitos.pdf)

**Comment by salathiel1999** [comment]
Calificación = 30 %

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
